services:
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    networks:
      - telemetry
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: "grafana/grafana-oss"
    ports:
      - "6060:3000"
    networks:
      - telemetry
networks:
  telemetry:
    driver: bridge